### PR TITLE
repo: Update license information

### PR DESCRIPTION
**Pull request by Yuggupta27**
Update license information.

Closes: #6 

Signed-off-by: Yug Gupta <yuggupta27@gmail.com>

### CODE REVIEW

**Comment by Yuggupta27** [comment]
Hi @leseb , Can we have access to @Madhu-1 as well? As he is also one of the contributors and is helping a lot towards the betterment of the tool?

**Review by subhamkrai — APPROVED** [review]
LGTM

**Comment by leseb** [comment]
> Hi @leseb , Can we have write access to @Madhu-1 as well? As he is also one of the contributors and is helping a lot towards the betterment of the tool?

Done.

**Comment by Yuggupta27** [comment]
> > Hi @leseb , Can we have write access to @Madhu-1 as well? As he is also one of the contributors and is helping a lot towards the betterment of the tool?
> 
> Done.

Thanks :)

**Review by Madhu-1 — APPROVED** [review]

**Pull request merged**
